#!/usr/bin/env bash
# Builds the upload archive for cPanel / GoDaddy Node.js hosting.
#
#   npm run package
#
# Produces dist/zvky-backend-godaddy.zip containing the application source and
# a ready .env, but no node_modules — cPanel installs dependencies itself with
# "Run NPM Install", which also builds anything platform-specific correctly.
#
# Database credentials are read from the environment so that none of them are
# ever written into a file that is committed:
#
#   DB_NAME=... DB_USER=... DB_PASSWORD=... npm run package
#
# Anything not supplied is left as a placeholder in the packaged .env for you
# to fill in on the server.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT/dist"
STAGE="$OUT_DIR/zvky-backend"
ZIP="$OUT_DIR/zvky-backend-godaddy.zip"

rm -rf "$STAGE" "$ZIP"
mkdir -p "$STAGE"

# The bulk-upload sample, generated from the column spec the importer validates
# against rather than kept by hand. The checked-in copy had drifted two rewrites
# behind — it still described the seven-column format, so the one file meant to
# show a studio the right shape was itself rejected by the importer.
node -e "process.stdout.write(require('$ROOT/src/asset-import').buildTemplateCsv())" \
  > "$ROOT/sample-bulk-import.csv"

# Application files only. node_modules, .git, uploads and any local .env stay out.
for item in app.js package.json README.md DEPLOY-GODADDY.md sample-bulk-import.csv src public sql; do
  [ -e "$ROOT/$item" ] && cp -r "$ROOT/$item" "$STAGE/"
done
cp "$ROOT/.env.example" "$STAGE/.env.example"

# uploads/ must exist and be writable; keep it in the archive but empty.
mkdir -p "$STAGE/uploads"
cat > "$STAGE/uploads/.gitkeep" <<'EOF'
EOF

# A JWT secret is generated per build so no two deployments share one, and so
# that a real secret never has to live in the repository.
JWT_SECRET_VALUE="${JWT_SECRET:-$(node -e "console.log(require('crypto').randomBytes(48).toString('hex'))")}"

cat > "$STAGE/.env" <<EOF
# Generated by scripts/build-godaddy-zip.sh — edit on the server as needed.

DB_HOST=${DB_HOST:-localhost}
DB_PORT=${DB_PORT:-3306}
DB_NAME=${DB_NAME:-your_database_name}
DB_USER=${DB_USER:-your_database_user}
DB_PASSWORD=${DB_PASSWORD:-your_database_password}

JWT_SECRET=${JWT_SECRET_VALUE}

PORT=${PORT:-4000}
CORS_ORIGIN=${CORS_ORIGIN:-https://your-domain.com}
TRUST_PROXY=1

LOGIN_RATE_MAX=100
LOGIN_RATE_WINDOW_MINUTES=15

# --- IP allowlist ---
# Monitor is also the built-in default; stated here so it is visible. A fresh
# deployment must not be able to lock its own administrator out before anyone
# has confirmed which address this server actually sees. Nothing is blocked;
# what would have been blocked is written to the log.
#
# To turn the restriction on:
#   1. Sign in and open Settings -> Allowed IP Addresses.
#   2. Read the "You are connecting from" line and add that address.
#   3. Set IP_ALLOWLIST_EMERGENCY below to an address you can reach from
#      somewhere else, so a mistake is recoverable without database surgery.
#   4. Change the line below to enforce and restart.
IP_ALLOWLIST_MODE=monitor
# IP_ALLOWLIST_EMERGENCY=
# IP_ALLOWLIST_BYPASS_TOKEN=
EOF

cd "$OUT_DIR"
zip -qr "$(basename "$ZIP")" "zvky-backend"
cd "$ROOT"
rm -rf "$STAGE"

echo "Built $ZIP"
unzip -l "$ZIP" | tail -3
