-- Zvky Pipeline Tracker — MySQL / MariaDB schema
--
-- Fresh install:
--   mysql -u <user> -p <database> < sql/schema.sql
--
-- On cPanel (GoDaddy), create the database and user first under
-- "MySQL Databases", then import this file through phpMyAdmin.
--
-- Ids are CHAR(36) UUIDs generated by the application, so this schema works
-- the same on MySQL 5.7, MySQL 8 and MariaDB.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS users (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  `name`        VARCHAR(255) NOT NULL,
  email         VARCHAR(191) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  -- One of the keys in src/roles.js. Kept as a VARCHAR rather than an ENUM so
  -- the studio can add a designation without an schema migration; the API
  -- validates it against the role catalogue on every write.
  `role`        VARCHAR(64)  NOT NULL,
  manager_id    CHAR(36)     NULL,
  team_lead_id  CHAR(36)     NULL,
  -- Unix epoch seconds, not DATETIME: this is compared against a JWT's `iat`
  -- claim, and epoch seconds carry no timezone for the two to disagree about.
  -- Any token issued before this moment is refused, which signs out every
  -- other device when someone changes their password.
  password_changed_at BIGINT UNSIGNED NULL,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_users_email (email),
  KEY idx_users_manager (manager_id),
  KEY idx_users_teamlead (team_lead_id),
  KEY idx_users_role (`role`),
  CONSTRAINT fk_users_manager   FOREIGN KEY (manager_id)   REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_users_team_lead FOREIGN KEY (team_lead_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS projects (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  `name`     VARCHAR(255) NOT NULL,
  `code`     VARCHAR(64)  NULL,
  owner_id   CHAR(36)     NOT NULL,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_projects_owner (owner_id),
  CONSTRAINT fk_projects_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS project_team_leads (
  project_id CHAR(36) NOT NULL,
  user_id    CHAR(36) NOT NULL,
  PRIMARY KEY (project_id, user_id),
  KEY idx_ptl_user (user_id),
  CONSTRAINT fk_ptl_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_ptl_user    FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS project_coordinators (
  project_id CHAR(36) NOT NULL,
  user_id    CHAR(36) NOT NULL,
  PRIMARY KEY (project_id, user_id),
  KEY idx_pc_user (user_id),
  CONSTRAINT fk_pc_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_pc_user    FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Status pipeline:
--  not_started -> in_progress -> pending_tl_review -> (tl_changes_requested <-> pending_tl_review)
--    -> pending_cd_review -> (cd_changes_requested <-> pending_cd_review)
--    -> approved_for_client -> delivered
CREATE TABLE IF NOT EXISTS assets (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  `code`        VARCHAR(64)  NOT NULL,
  `name`        VARCHAR(255) NOT NULL,
  `type`        VARCHAR(32)  NOT NULL,
  `status`      VARCHAR(32)  NOT NULL DEFAULT 'not_started',
  priority      VARCHAR(8)   NOT NULL DEFAULT 'med',
  project_id    CHAR(36)     NOT NULL,
  assignee_id   CHAR(36)     NULL,
  man_hours     DECIMAL(6,1) NULL,
  due_date      DATE         NULL,
  description   TEXT         NULL,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_assets_project (project_id),
  KEY idx_assets_assignee (assignee_id),
  KEY idx_assets_status (`status`),
  CONSTRAINT fk_assets_project  FOREIGN KEY (project_id)  REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_assets_assignee FOREIGN KEY (assignee_id) REFERENCES users(id)    ON DELETE SET NULL,
  CONSTRAINT chk_assets_type   CHECK (`type` IN ('character','prop','environment','fx','animation','background')),
  CONSTRAINT chk_assets_status CHECK (`status` IN (
    'not_started','in_progress','pending_tl_review','tl_changes_requested',
    'pending_cd_review','cd_changes_requested','approved_for_client','delivered'
  )),
  CONSTRAINT chk_assets_priority CHECK (priority IN ('low','med','high'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tasks (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  asset_id   CHAR(36)     NOT NULL,
  `name`     VARCHAR(255) NOT NULL,
  done       TINYINT(1)   NOT NULL DEFAULT 0,
  `position` INT          NOT NULL DEFAULT 0,
  KEY idx_tasks_asset (asset_id),
  CONSTRAINT fk_tasks_asset FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notes (
  id         CHAR(36) NOT NULL PRIMARY KEY,
  asset_id   CHAR(36) NOT NULL,
  author_id  CHAR(36) NULL,
  `text`     TEXT     NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_notes_asset (asset_id),
  CONSTRAINT fk_notes_asset  FOREIGN KEY (asset_id)  REFERENCES assets(id) ON DELETE CASCADE,
  CONSTRAINT fk_notes_author FOREIGN KEY (author_id) REFERENCES users(id)  ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Every file an artist uploads for review is a version. stage records which
-- review loop it was submitted into, so reviewers see the right history.
CREATE TABLE IF NOT EXISTS asset_versions (
  id             CHAR(36)     NOT NULL PRIMARY KEY,
  asset_id       CHAR(36)     NOT NULL,
  version_number INT          NOT NULL,
  stage          VARCHAR(8)   NOT NULL,
  file_name      VARCHAR(255) NOT NULL,
  file_path      VARCHAR(255) NOT NULL,
  file_size      INT          NULL,
  uploaded_by    CHAR(36)     NULL,
  created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_versions_asset (asset_id),
  CONSTRAINT fk_versions_asset  FOREIGN KEY (asset_id)    REFERENCES assets(id) ON DELETE CASCADE,
  CONSTRAINT fk_versions_author FOREIGN KEY (uploaded_by) REFERENCES users(id)  ON DELETE SET NULL,
  CONSTRAINT chk_versions_stage CHECK (stage IN ('tl','cd'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- A reviewer's decision on a version: approve, or request changes with notes.
CREATE TABLE IF NOT EXISTS feedback (
  id         CHAR(36)   NOT NULL PRIMARY KEY,
  asset_id   CHAR(36)   NOT NULL,
  version_id CHAR(36)   NULL,
  stage      VARCHAR(8) NOT NULL,
  decision   VARCHAR(24) NOT NULL,
  given_by   CHAR(36)   NULL,
  `text`     TEXT       NULL,
  created_at DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_feedback_asset (asset_id),
  CONSTRAINT fk_feedback_asset   FOREIGN KEY (asset_id)   REFERENCES assets(id)         ON DELETE CASCADE,
  CONSTRAINT fk_feedback_version FOREIGN KEY (version_id) REFERENCES asset_versions(id) ON DELETE SET NULL,
  CONSTRAINT fk_feedback_author  FOREIGN KEY (given_by)   REFERENCES users(id)          ON DELETE SET NULL,
  CONSTRAINT chk_feedback_stage    CHECK (stage IN ('tl','cd')),
  CONSTRAINT chk_feedback_decision CHECK (decision IN ('approved','changes_requested'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
