-- Zvky Pipeline Tracker — MySQL / MariaDB schema
--
-- Fresh install:
--   mysql -u <user> -p <database> < sql/schema.sql
--
-- On cPanel (GoDaddy), create the database and user first under
-- "MySQL Databases", then import this file through phpMyAdmin.
--
-- Ids are CHAR(36) UUIDs generated by the application, so this schema works
-- the same on MySQL 5.7, MySQL 8 and MariaDB.

SET NAMES utf8mb4;

-- --------------------------------------------------------------------------
-- Reference data: the value lists behind the dropdowns. These used to be
-- arrays in the source and CHECK constraints here, which meant a code change
-- and a deploy every time the studio wanted a new asset type or designation.
-- A Super Admin manages them in Settings; src/migrate.js fills them in from
-- the previous hardcoded values on first start.
--
-- `key` is what assets.type, assets.priority and users.role actually hold. It
-- is generated once and never changes, so renaming a value in Settings leaves
-- every record that uses it untouched. is_system marks the values the app
-- depends on by name and refuses to delete.
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS asset_types (
  id          CHAR(36)     NOT NULL PRIMARY KEY,
  `key`       VARCHAR(64)  NOT NULL,
  label       VARCHAR(100) NOT NULL,
  -- Asset codes are built from this: CHR-001, ENV-014.
  code_prefix VARCHAR(8)   NOT NULL,
  color       VARCHAR(16)  NULL,
  position    INT          NOT NULL DEFAULT 0,
  is_active   TINYINT(1)   NOT NULL DEFAULT 1,
  is_system   TINYINT(1)   NOT NULL DEFAULT 0,
  created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_asset_types_key (`key`),
  UNIQUE KEY uq_asset_types_prefix (code_prefix)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS priorities (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  `key`      VARCHAR(64)  NOT NULL,
  label      VARCHAR(100) NOT NULL,
  color      VARCHAR(16)  NULL,
  position   INT          NOT NULL DEFAULT 0,
  is_active  TINYINT(1)   NOT NULL DEFAULT 1,
  is_system  TINYINT(1)   NOT NULL DEFAULT 0,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_priorities_key (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS roles (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  `key`      VARCHAR(64)  NOT NULL,
  label      VARCHAR(150) NOT NULL,
  -- The heading a role sits under in the picker: Art, Animation, Engineering.
  group_name VARCHAR(100) NOT NULL,
  -- Which capability set applies. See src/role-tiers.js.
  tier       VARCHAR(32)  NOT NULL,
  color      VARCHAR(16)  NULL,
  -- Doubles as seniority: higher sorts first within a group.
  position   INT          NOT NULL DEFAULT 0,
  is_active  TINYINT(1)   NOT NULL DEFAULT 1,
  is_system  TINYINT(1)   NOT NULL DEFAULT 0,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_roles_key (`key`),
  KEY idx_roles_tier (tier)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------------------------
-- Which addresses may reach this application at all. Managed by a Super Admin
-- under Settings; enforced by src/middleware/ip-allowlist.js ahead of
-- authentication.
--
-- The ways back in after a bad entry live in the environment, not here — see
-- IP_ALLOWLIST_* in .env.example. A safeguard stored in the thing it safeguards
-- is not a safeguard.
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ip_allowlist (
  id               CHAR(36)     NOT NULL PRIMARY KEY,
  -- A single address or a CIDR range, stored canonically: 106.51.81.61,
  -- 106.51.81.0/24, 2001:db8::/32.
  address          VARCHAR(64)  NOT NULL,
  label            VARCHAR(120) NULL,
  is_active        TINYINT(1)   NOT NULL DEFAULT 1,
  created_by_id    CHAR(36)     NULL,
  -- Kept alongside the id so the trail survives the account being deleted.
  created_by_email VARCHAR(191) NULL,
  created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_ip_allowlist_address (address),
  KEY idx_ip_allowlist_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Every change, including removals. After a lockout the useful question is who
-- removed what, so this is deliberately append-only and outlives the entries.
CREATE TABLE IF NOT EXISTS ip_allowlist_audit (
  id          CHAR(36)     NOT NULL PRIMARY KEY,
  action      VARCHAR(24)  NOT NULL,
  address     VARCHAR(64)  NULL,
  label       VARCHAR(120) NULL,
  actor_id    CHAR(36)     NULL,
  actor_email VARCHAR(191) NULL,
  actor_ip    VARCHAR(64)  NULL,
  detail      VARCHAR(255) NULL,
  created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_ip_audit_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  `name`        VARCHAR(255) NOT NULL,
  email         VARCHAR(191) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  -- One of the keys in src/roles.js. Kept as a VARCHAR rather than an ENUM so
  -- the studio can add a designation without an schema migration; the API
  -- validates it against the role catalogue on every write.
  `role`        VARCHAR(64)  NOT NULL,
  -- Who created this account. Despite the name this is not a reporting line:
  -- it gates who may edit or remove the user ("you can only change users you
  -- added"). Left alone deliberately — see reports_to_id below.
  manager_id    CHAR(36)     NULL,
  -- The work hierarchy for contributors: who reviews their assets. Drives
  -- team-scoped permissions, so it is not the org chart either.
  team_lead_id  CHAR(36)     NULL,
  -- The org chart: who this person reports to. Separate from both of the above
  -- because changing an org chart must not change anybody's permissions, and
  -- it applies to every designation rather than only to contributors.
  -- NULL for the Leadership tier, who sit at the top and report to no one.
  reports_to_id CHAR(36)     NULL,
  -- Unix epoch seconds, not DATETIME: this is compared against a JWT's `iat`
  -- claim, and epoch seconds carry no timezone for the two to disagree about.
  -- Any token issued before this moment is refused, which signs out every
  -- other device when someone changes their password.
  password_changed_at BIGINT UNSIGNED NULL,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_users_email (email),
  KEY idx_users_manager (manager_id),
  KEY idx_users_reports_to (reports_to_id),
  KEY idx_users_teamlead (team_lead_id),
  KEY idx_users_role (`role`),
  CONSTRAINT fk_users_manager   FOREIGN KEY (manager_id)   REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_users_team_lead FOREIGN KEY (team_lead_id) REFERENCES users(id) ON DELETE SET NULL,
  -- SET NULL rather than CASCADE: removing a manager must orphan their reports,
  -- never delete them.
  CONSTRAINT fk_users_reports_to FOREIGN KEY (reports_to_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Permissions granted to one person, on top of whatever their role already
-- allows. Additive only: a row here adds a permission, and there is no row
-- shape that takes one away — removing something a role grants means changing
-- the role. See src/permission-catalog.js.
CREATE TABLE IF NOT EXISTS user_permissions (
  user_id         CHAR(36)     NOT NULL,
  permission_key  VARCHAR(64)  NOT NULL,
  granted_by_id   CHAR(36)     NULL,
  granted_by_email VARCHAR(191) NULL,
  created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, permission_key),
  KEY idx_user_permissions_user (user_id),
  CONSTRAINT fk_uperm_user  FOREIGN KEY (user_id)       REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_uperm_actor FOREIGN KEY (granted_by_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Who changed whose permissions, and when. Append-only, and outlives both the
-- grant and the accounts involved.
CREATE TABLE IF NOT EXISTS permission_audit (
  id             CHAR(36)     NOT NULL PRIMARY KEY,
  seq            BIGINT       NOT NULL AUTO_INCREMENT UNIQUE,
  subject_id     CHAR(36)     NULL,
  subject_email  VARCHAR(191) NULL,
  permission_key VARCHAR(64)  NOT NULL,
  action         VARCHAR(16)  NOT NULL,
  actor_id       CHAR(36)     NULL,
  actor_email    VARCHAR(191) NULL,
  created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_perm_audit_subject (subject_id, seq)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS projects (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  `name`     VARCHAR(255) NOT NULL,
  `code`     VARCHAR(64)  NULL,
  owner_id   CHAR(36)     NOT NULL,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_projects_owner (owner_id),
  CONSTRAINT fk_projects_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS project_team_leads (
  project_id CHAR(36) NOT NULL,
  user_id    CHAR(36) NOT NULL,
  PRIMARY KEY (project_id, user_id),
  KEY idx_ptl_user (user_id),
  CONSTRAINT fk_ptl_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_ptl_user    FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS project_coordinators (
  project_id CHAR(36) NOT NULL,
  user_id    CHAR(36) NOT NULL,
  PRIMARY KEY (project_id, user_id),
  KEY idx_pc_user (user_id),
  CONSTRAINT fk_pc_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_pc_user    FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Status pipeline:
--  not_started -> in_progress -> pending_tl_review -> (tl_changes_requested <-> pending_tl_review)
--    -> pending_cd_review -> (cd_changes_requested <-> pending_cd_review)
--    -> approved_for_client -> delivered
-- Everyone else's project. Coordinators sit in project_coordinators and leads in
-- project_team_leads; contributors had no link to a project at all, so the
-- studio's artists could not be assigned to one. This is that link.
CREATE TABLE IF NOT EXISTS project_members (
  project_id CHAR(36) NOT NULL,
  user_id    CHAR(36) NOT NULL,
  PRIMARY KEY (project_id, user_id),
  KEY idx_pm_user (user_id),
  CONSTRAINT fk_pm_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_pm_user    FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS assets (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  `code`        VARCHAR(64)  NOT NULL,
  `name`        VARCHAR(255) NOT NULL,
  `type`        VARCHAR(32)  NOT NULL,
  `status`      VARCHAR(32)  NOT NULL DEFAULT 'not_started',
  priority      VARCHAR(8)   NOT NULL DEFAULT 'med',
  project_id    CHAR(36)     NOT NULL,
  assignee_id   CHAR(36)     NULL,
  -- Whose desk this is on right now, which is not the same as its status: an
  -- asset in CD Changes sits with the team lead until they relay the notes, and
  -- with the assignee afterwards, without the status moving. NULL means a
  -- review queue that whoever holds that gate picks up.
  routed_to_id  CHAR(36)     NULL,
  man_hours     DECIMAL(6,1) NULL,
  due_date      DATE         NULL,
  description   TEXT         NULL,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_assets_project (project_id),
  KEY idx_assets_assignee (assignee_id),
  KEY idx_assets_status (`status`),
  KEY idx_assets_routed (routed_to_id),
  CONSTRAINT fk_assets_project  FOREIGN KEY (project_id)  REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_assets_assignee FOREIGN KEY (assignee_id) REFERENCES users(id)    ON DELETE SET NULL,
  CONSTRAINT fk_assets_routed   FOREIGN KEY (routed_to_id) REFERENCES users(id)   ON DELETE SET NULL,
  -- No CHECK on `type` or priority: both are managed in Settings and validated
  -- against the asset_types / priorities tables. `status` keeps its constraint
  -- because it is a fixed pipeline, not a list anyone edits.
  CONSTRAINT chk_assets_status CHECK (`status` IN (
    'not_started','in_progress','pending_tl_review','tl_changes_requested',
    'pending_cd_review','cd_changes_requested','approved_for_client','delivered'
  ))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tasks (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  asset_id   CHAR(36)     NOT NULL,
  `name`     VARCHAR(255) NOT NULL,
  done       TINYINT(1)   NOT NULL DEFAULT 0,
  `position` INT          NOT NULL DEFAULT 0,
  KEY idx_tasks_asset (asset_id),
  CONSTRAINT fk_tasks_asset FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notes (
  id         CHAR(36) NOT NULL PRIMARY KEY,
  asset_id   CHAR(36) NOT NULL,
  author_id  CHAR(36) NULL,
  `text`     TEXT     NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_notes_asset (asset_id),
  CONSTRAINT fk_notes_asset  FOREIGN KEY (asset_id)  REFERENCES assets(id) ON DELETE CASCADE,
  CONSTRAINT fk_notes_author FOREIGN KEY (author_id) REFERENCES users(id)  ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Every file an artist uploads for review is a version. stage records which
-- review loop it was submitted into, so reviewers see the right history.
CREATE TABLE IF NOT EXISTS asset_versions (
  id             CHAR(36)     NOT NULL PRIMARY KEY,
  asset_id       CHAR(36)     NOT NULL,
  version_number INT          NOT NULL,
  stage          VARCHAR(8)   NOT NULL,
  -- Where the work is. Mandatory for anything submitted through the review
  -- form; NULL only on rows that predate it and carry a file instead.
  link           VARCHAR(2048) NULL,
  -- The submitter's own notes. Optional by design: a link with nothing to say
  -- about it is a perfectly ordinary submission.
  description    TEXT         NULL,
  -- Kept for submissions made before the form took a link, and still allowed
  -- as an optional attachment alongside one.
  file_name      VARCHAR(255) NULL,
  file_path      VARCHAR(255) NULL,
  file_size      INT          NULL,
  uploaded_by    CHAR(36)     NULL,
  created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_versions_asset (asset_id),
  CONSTRAINT fk_versions_asset  FOREIGN KEY (asset_id)    REFERENCES assets(id) ON DELETE CASCADE,
  CONSTRAINT fk_versions_author FOREIGN KEY (uploaded_by) REFERENCES users(id)  ON DELETE SET NULL,
  CONSTRAINT chk_versions_stage CHECK (stage IN ('tl','cd'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- A reviewer's decision on a version: approve, or request changes with notes.
-- Every move an asset makes, in order: assignment, each submission, each review
-- decision, the relay, delivery. The submission and review tables hold the
-- detail; this holds the sequence, so the asset detail view can show the whole
-- back-and-forth rather than only the current state.
--
-- Append-only. Nothing here is ever updated or deleted while the asset lives.
CREATE TABLE IF NOT EXISTS asset_events (
  id          CHAR(36)     NOT NULL PRIMARY KEY,
  -- The order things happened in. created_at is only accurate to the second,
  -- and a review round is quicker than that — submit, approve and relay land in
  -- the same second routinely, and sorting by timestamp then scrambles them.
  -- This is the sequence the history is read in.
  seq         BIGINT       NOT NULL AUTO_INCREMENT UNIQUE,
  asset_id    CHAR(36)     NOT NULL,
  -- The transition that was made: assign, submit, tl_approve, tl_request_changes,
  -- cd_approve, cd_request_changes, relay, deliver.
  action      VARCHAR(32)  NOT NULL,
  from_status VARCHAR(32)  NULL,
  to_status   VARCHAR(32)  NOT NULL,
  actor_id    CHAR(36)     NULL,
  -- Kept alongside the id so the trail survives the account being deleted.
  actor_email VARCHAR(191) NULL,
  -- Feedback text, or the submitter's description, or a plain explanation.
  note        TEXT         NULL,
  -- The submission this event concerns, when there is one.
  version_id  CHAR(36)     NULL,
  routed_to_id CHAR(36)    NULL,
  created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_events_asset (asset_id, seq),
  CONSTRAINT fk_events_asset  FOREIGN KEY (asset_id)   REFERENCES assets(id)         ON DELETE CASCADE,
  CONSTRAINT fk_events_actor  FOREIGN KEY (actor_id)   REFERENCES users(id)          ON DELETE SET NULL,
  CONSTRAINT fk_events_version FOREIGN KEY (version_id) REFERENCES asset_versions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS feedback (
  id         CHAR(36)   NOT NULL PRIMARY KEY,
  asset_id   CHAR(36)   NOT NULL,
  version_id CHAR(36)   NULL,
  stage      VARCHAR(8) NOT NULL,
  decision   VARCHAR(24) NOT NULL,
  given_by   CHAR(36)   NULL,
  `text`     TEXT       NULL,
  created_at DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_feedback_asset (asset_id),
  CONSTRAINT fk_feedback_asset   FOREIGN KEY (asset_id)   REFERENCES assets(id)         ON DELETE CASCADE,
  CONSTRAINT fk_feedback_version FOREIGN KEY (version_id) REFERENCES asset_versions(id) ON DELETE SET NULL,
  CONSTRAINT fk_feedback_author  FOREIGN KEY (given_by)   REFERENCES users(id)          ON DELETE SET NULL,
  CONSTRAINT chk_feedback_stage    CHECK (stage IN ('tl','cd')),
  CONSTRAINT chk_feedback_decision CHECK (decision IN ('approved','changes_requested'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
